config/routes.rb
Rails.application.routes.draw do
  get 'try/api'
  get 'home/show'
  devise_for :users
  get 'home/index'
  root 'home#index'

  namespace 'api' do
    namespace 'v1' do
      resources :markers
      resources :users
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :user

  validates :lati, presence: true
  validates :long, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :markers	
  before_create -> {self.api_token = generate_token}

  private
 
  def generate_token
    loop do
      token = SecureRandom.hex
      return token unless User.exists?({api_token: token})
    end
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session ,:authenticate_user_from_token!

  def destroy_session
    request.session_options[:skip] = true
  end

    private
       def authenticate_user_from_token!
         if !params['api_token']
          error = {
            error: "No 'api_token' given in params, Authorization need it.",
            code: 400
          }
          render :json => error, :status => :bad_params
         else
           @user = nil
           User.find_each do |u|
             if Devise.secure_compare(u.api_token, params['api_token'])
               @user = u
             end
            end
            erro2 = {
            error: "INVALID API TOKEN, CHECK",
            code: 401
          }
            if @user == nil
              render :json => erro2, :status => :unauthorizated
            end

         end
       end

end

app/controllers/api/v1/markers_controller.rb
class Api::V1::MarkersController < Api::V1::BaseController
    def index
        @markers = @user.markers.all
        respond_to do |format|
            format.json { render :json => @markers.to_json, :status => :ok}
        end
    end

    def create
      data =  request.body.read()
      @marker = @user.markers.new(JSON.parse(data))
        if @marker.save
            render json: @marker, status: :created
        else
            render json: @marker.errors, status: :unprocessable_entity
        end
    end
    

    def update
    end

    def destroy
    end

    def show
    end
    
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
    def index
        @users = User.all
        respond_to do |format|
            format.json { render :json => @users.to_json, :status => :ok}
        end
    end

    def create
    end

    def update
    end

    def destroy
    end

    def show
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  protected
    def after_sign_in_path_for(resource)
        home_show_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def show
    if user_signed_in?
      @markers = current_user.markers.all

      if @markers.empty?
        @flati = 0
        @flong = 0
      else
        @flati = @markers.first.lati
        @flong = @markers.first.long
      end
    end
  end
  
end

app/controllers/try_controller.rb
class TryController < ApplicationController
  def api
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/try_helper.rb
module TryHelper
end

app/views/home/index.html.erb
<h1> Welcome to UserMapsApi! </h1>

<%= button_to "Log In", new_user_session_url, method: :get %>
<%= button_to "Sign In", new_user_registration_url, method: :get %>

app/views/home/show.html.erb
<script>
  var map;
  function initMap() {
    var home = {lat: <%= @flati %>, lng: <%= @flong %> };
    map = new google.maps.Map(document.getElementById('map'), {zoom: 15, center: home});
    <% @markers.each do |m| %>
          var point = {lat: <%= m.lati %>, lng: <%= m.long %>};
          var marker = new google.maps.Marker({position: point, map: map, title:"marker" });
    <% end %>
  }
</script>

<div class="container">
  <h1>Welcome - Home</h1>
  <div class="panel panel-default">
    <div class="panel-heading">Email:</div>
    <div class="panel-body"> <%= current_user.email %> </div>
  </div>
</div>
<br></br>
<center> <div class="row">
   <div class="col-sm-4">
     <%= button_to "Log out", destroy_user_session_url, method: :delete %>
   </div>
   <div class="col-sm-4"><%= link_to '<button type="button" class="btn btn-info">Try API by your self!</button>'.html_safe, try_api_path %></div>
   <div class="col-sm-4">You have '<%= @markers.size %>' markers</div>
</div> </center>

<br></br>

<div class="container">
  <h2>Api - Key</h2>
  <div>If you want to use the API and send position marks, use this secure TOKEN </div>
  <div class="panel panel-default">
    <div class="panel-body"> <%= current_user.api_token %></div>
  </div>
</div>
<br></br>

<h3>Actual Markers</h3>
    
<div id="map"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UmarkersApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVmUsfWZKkYQ8mlvE3N70jbjqnca63KRU&callback=initMap"> </script>

    <style>
    /* Set the size of the div element that contains the map */
   #map {
     height: 500px;  /* The height is 400 pixels */
     width: 100%;  /* The width is the width of the web page */
    }
    </style>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/try/api.html.erb
 <p id="demo"></p>
<center>
 <div class="panel panel-success">
      <div class="panel-heading"><h1>Api - Try</h1></div>
      <div class="panel-body">This will send a POST to the url '/api/v1/markers' with your actual position, using the API token <%= current_user.api_token%> as 'api_token' parameter. After this, you can check your new marker in your home page</div>
      <div class="panel-footer"> <button type="button" class="btn btn-danger" onclick="getLocation()">Try It</button>
 - <%= link_to '<button type="button" class="btn btn-info">Go home</button>'.html_safe, home_show_path %></div>  </div> </center>
<script>
  var x = document.getElementById("demo");

  function getLocation() {
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition);
      } else { 
          x.innerHTML = "Geolocation is not supported by this browser.";
      }
  }

  function showPosition(position) {
    var http =new XMLHttpRequest();
    var url = "../api/v1/markers?api_token=<%= current_user.api_token %>"
    var longitude = position.coords.longitude;
    var latitude = position.coords.latitude;
    http.open("POST",url,true);
    http.setRequestHeader("Content-Type","application/json;charset=UTF-8");
    http.onreadystatechange = function(){
      if(http.readyState == 4 && http.status == 200){
        alert(http.responseText);
      }
    }
    http.send(JSON.stringify({long:longitude, lati:latitude}));
  }
  </script>